version: 2
jobs:
  build:
    docker:
      - image: gaumala/blog-arch:0.2
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            # find a cache for the same stack.yaml
            - deps-{{ checksum "api/stack.yaml" }}-{{ checksum "frontend/yarn.lock" }}
            # when missing reuse the latest cache
            - deps-
      - run:
          name: Resolve/Update API Server Dependencies
          command: |
            cd api 
            stack setup
            stack build --dependencies-only
      - run:
          name: Resolve/Update Frontend Dependencies
          command: |
            cd frontend 
            yarn
      - save_cache:
          name: Cache Dependencies
          key: deps-{{ checksum "api/stack.yaml" }}-{{ checksum "frontend/yarn.lock" }}
          paths:
            - ~/.stack
            - ./api/.stack-work
            - ./frontend/node_modules
      - run:
          name: Build Frontend App
          command: |
            cd frontend
            yarn build
      - run:
          name: Build API App
          command: |
            cd api 
            stack build --pedantic
      - run:
          name: Test API App
          command: |
            cd api
            stack test
      
