version: 2
jobs:
  build:
    docker:
      - image: gaumala/blog-arch:0.4
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - deps-{{ checksum "api/stack.yaml" }}-{{ checksum "static/stack.yaml" }}-{{ checksum "frontend/yarn.lock" }}
            # when missing reuse the latest cache
            - deps-
      - run:
          name: Resolve/Update API Server Dependencies
          command: |
            cd api 
            stack setup
            stack build --test --dependencies-only
      - run:
          name: Resolve/Update Static Site Dependencies
          command: |
            cd static 
            stack setup
            # this is pretty big so disable optimizations and limit
            # to one job to avoid running out of memory
            stack build --dependencies-only -j1 --ghc-options -O0 
      - run:
          name: Resolve/Update Frontend Dependencies
          command: |
            cd frontend 
            yarn
      - save_cache:
          name: Cache Dependencies
          key: deps-{{ checksum "api/stack.yaml" }}--{{ checksum "static/stack.yaml" }}-{{ checksum "frontend/yarn.lock" }}
          paths:
            - ~/.stack
            - ./api/.stack-work
            - ./static/.stack-work
            - ./frontend/node_modules
      - run:
          name: Build Frontend App
          command: |
            cd frontend
            yarn build
      - run:
          name: Build API App
          command: |
            cd api 
            stack build --pedantic
      - run:
          name: Test API App
          command: |
            cd api
            stack test
      - run:
          name: Build Static Site Generator
          command: |
            cd static
            stack build --pedantic --ghc-options -fno-warn-type-defaults
      - run:
          name: Generate Pages
          command: |
            cd static
            stack exec site build
      
