# Stack configuration for Haskell project
#
# Modern best practices and commonly used options are documented below.
# For comprehensive documentation, see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# Resolver specifies the Stackage snapshot or compiler version
# This determines:
# - GHC version (9.6.6 for lts-22.43)
# - Curated package versions
# - Compatibility guarantees
#
# Format options:
# - lts-X.Y         (Stable LTS snapshot)
# - nightly-YYYY-MM-DD  (Nightly snapshot)
# - ghc-X.Y.Z       (Specific GHC version)
# - ./custom.yaml    (Local snapshot file)
# - https://example.com/snapshots/2024-01-01.yaml (Remote snapshot)
resolver: lts-22.43

# Project packages to build
# Supports multiple formats:
#
# Local packages:
# - .
# - ./subdirectory
#
# Remote packages:
# - https://example.com/package-1.0.0.tar.gz
#
# Git repositories:
# - location:
#     git: https://github.com/user/repo.git
#     commit: abc123
#   subdirs:
#   - core
#   - plugins
packages:
- .

# Additional dependencies not in the resolver
# Useful for:
# - Packages not yet in Stackage
# - Specific versions needed
# Example:
# extra-deps:
# - acme-missiles-0.4
# - git: https://github.com/user/repo.git
#   commit: abc123
extra-deps: []

# Package flag overrides
# Example:
# flags:
#   library:
#     dev-mode: true
flags: {}

# Additional configuration
# system-ghc: true  # Use system GHC instead of Stack-managed
# require-stack-version: ">=2.11"  # Minimum Stack version
# compiler-check: newer-minor  # Allow newer GHC minor versions

# Additional paths (rarely needed)
# extra-include-dirs: [/path/to/includes]
# extra-lib-dirs: [/path/to/libs]
# extra-package-dbs: [/path/to/pdb]
