name:                api
version:             0.1.0.0
github:              "GAumala/blog"
license:             BSD3
author:              "Gabriel Aumala"
maintainer:          "gabriel@criptext.com"
copyright:           "2018 Gabriel Aumala"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/GAumala/blog>

dependencies:
- base >= 4.7 && < 5
- beam-core
- beam-sqlite
- directory
- filepath
- http-types
- process
- sqlite-simple
- scotty
- text
- warp

library:
  source-dirs: src

executables:
  api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api

tests:
  api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - api
    - directory
    - filepath
    - hspec 
    - process
